name: Deploy to Staging

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Deploy the image
      run: |
        echo "Deployment success ✅"
